services:
  db:
    image: postgres:16
    environment:
      POSTRES_DB: inventory_manager
      POSTRES_USER: postres
      POSTRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - POSTGRESQL_PWD
    volumes:
      - pgdata:/var/lib/postgresql/data

  project:
    build: ./project
    ports:
      - "5003:5003"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

secrets:
  # this must match the .env var name
  POSTGRESQL_PWD:
    file: ./secrets/db_password.txt
